version: '3'
services:
  phone-list-fe:
    build: .
    ports:
      - 5002:8080
    volumes:
      - .:/app:rw
    command: sh
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
