version: '3'
services:
  phone-list-fe:
    build: .
    ports:
      - 5002:8080
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: yarn dev
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
